package com.eixox.models.bmf;

import java.util.LinkedList;
import java.util.List;

/**
 * As especies dos titulos negociados na serie histórica da Bmf Bovespa.
 * 
 * @author Rodrigo Portela
 *
 */
public class Especie {

	public final String sigla;
	public final String nome;

	public Especie(String sigla, String nome) {
		this.sigla = sigla;
		this.nome = nome;
	}

	public static final LinkedList<Especie> ESPECIES;

	static {

		ESPECIES = new LinkedList<Especie>();
		ESPECIES.add(new Especie("ON", "AÇÕES ORDINÁRIAS NOMINATIVAS"));
		ESPECIES.add(new Especie("PNA", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE A"));
		ESPECIES.add(new Especie("PNB", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE B"));
		ESPECIES.add(new Especie("PNC", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE C"));
		ESPECIES.add(new Especie("PND", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE D"));
		ESPECIES.add(new Especie("PNE", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE E"));
		ESPECIES.add(new Especie("PNF", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE F"));
		ESPECIES.add(new Especie("PNG", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE G"));
		ESPECIES.add(new Especie("PNH", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE H"));
		ESPECIES.add(new Especie("PN", "AÇÕES PREFERENCIAIS NOMINATIVAS"));
		ESPECIES.add(new Especie("PNV", "AÇÕES PREFERENCIAIS NOMINATIVAS COM DIREITO A VOTO"));
		ESPECIES.add(new Especie("OR", "AÇÕES ORDINÁRIAS NOMINATIVAS RESGATÁVEIS"));
		ESPECIES.add(new Especie("PRA", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE A RESGATÁVEIS"));
		ESPECIES.add(new Especie("PRB", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE B RESGATÁVEIS"));
		ESPECIES.add(new Especie("PRC", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE C RESGATÁVEIS"));
		ESPECIES.add(new Especie("PRD", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE D RESGATÁVEIS"));
		ESPECIES.add(new Especie("PRE", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE E RESGATÁVEIS"));
		ESPECIES.add(new Especie("PRF", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE F RESGATÁVEIS"));
		ESPECIES.add(new Especie("PRG", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE G RESGATÁVEIS"));
		ESPECIES.add(new Especie("PRH", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE H RESGATÁVEIS"));
		ESPECIES.add(new Especie("PNR", "AÇÕES PREFERENCIAIS NOMINATIVAS RESGATÁVEIS"));
		ESPECIES.add(new Especie("PRV", "AÇÕES PREFERENCIAIS NOMINATIVAS COM DIREITO A VOTO RESG"));
		ESPECIES.add(new Especie("ON P", "AÇÕES ORDINÁRIAS NOMINATIVAS COM DIREITOS DIFERENCIADOS"));
		ESPECIES.add(new Especie("PNA P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE A C/ DIREITOS DIFER"));
		ESPECIES.add(new Especie("PNB P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE B C/ DIREITOS DIFER"));
		ESPECIES.add(new Especie("PNC P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE C C/ DIREITOS DIFER"));
		ESPECIES.add(new Especie("PND P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE D C/ DIREITOS DIFER"));
		ESPECIES.add(new Especie("PNE P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE E C/ DIREITOS DIFER"));
		ESPECIES.add(new Especie("PNF P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE F C/ DIREITOS DIFER"));
		ESPECIES.add(new Especie("PNG P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE G C/ DIREITOS DIFER"));
		ESPECIES.add(new Especie("PNH P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE H C/ DIREITOS DIFER"));
		ESPECIES.add(new Especie("PN P", "AÇÕES PREFERENCIAIS NOMINATIVAS COM DIREITOS DIFERENCIADOS"));
		ESPECIES.add(new Especie("PNV P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE V C/ DIREITOS DIFER"));
		ESPECIES.add(new Especie("ON P", "AÇÕES ORDINÁRIAS NOMINATIVAS COM DIREITOS DIFERENCIADOS"));
		ESPECIES.add(new Especie("BDR", "BDR"));
		ESPECIES.add(new Especie("UNT", "CERTIFICADO DE DEPOSITO DE AÇÕES - MISCELÂNEA"));
		ESPECIES.add(new Especie("CDA", "CERTIFICADO DE DEPOSITO DE AÇÕES ORDINÁRIAS"));
		ESPECIES.add(new Especie("CPA", "CERTIFICADOS DE POTENCIAL ADICIONAL DE CONSTRUÇÃO E OPERAÇÃO"));
		ESPECIES.add(new Especie("RON", "CESTA DE AÇÕES ORDINÁRIAS NOMINATIVAS"));
		ESPECIES.add(new Especie("R", "CESTA DE AÇÕES NOMINATIVAS"));
		ESPECIES.add(new Especie("CI", "FUNDO DE INVESTIMENTO"));
		ESPECIES.add(new Especie("DIR", "DIREITOS DE SUBSCRIÇÃO MISCELÂNEA (BÔNUS, DEBÊNTURES, ETC)"));
		ESPECIES.add(new Especie("DIR ORD", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES ORDINÁRIAS"));
		ESPECIES.add(new Especie("DIR P/A", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE A"));
		ESPECIES.add(new Especie("DIR P/B", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE B"));
		ESPECIES.add(new Especie("DIR P/C", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE C"));
		ESPECIES.add(new Especie("DIR P/D", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE D"));
		ESPECIES.add(new Especie("DIR P/E", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE E"));
		ESPECIES.add(new Especie("DIR P/F", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE F"));
		ESPECIES.add(new Especie("DIR P/G", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE G"));
		ESPECIES.add(new Especie("DIR P/H", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE H"));
		ESPECIES.add(new Especie("DIR PRE", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS"));
		ESPECIES.add(new Especie("PRA REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES RESGATÁVEIS PREF. CLASSE A"));
		ESPECIES.add(new Especie("PRB REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES RESGATÁVEIS PREF. CLASSE B"));
		ESPECIES.add(new Especie("PRC REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES RESGATÁVEIS PREF. CLASSE C"));
		ESPECIES.add(new Especie("M1 REC", "RECIBO DE SUBSCRIÇÃO DE MISCELÂNEAS"));
		ESPECIES.add(new Especie("DIR PRA", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES RESGATÁVEIS PREF. CLASSE A"));
		ESPECIES.add(new Especie("DIR PRB", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES RESGATÁVEIS PREF. CLASSE B"));
		ESPECIES.add(new Especie("DIR PRC", "DIREITOS DE SUBSCRIÇÃO EM AÇÕES RESGATÁVEIS PREF. CLASSE C"));
		ESPECIES.add(new Especie("LFT", "LETRA FINANCEIRA DO TESOURO"));
		ESPECIES.add(new Especie("BNS ORD", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES ORDINÁRIAS"));
		ESPECIES.add(new Especie("BNS P/A", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE A"));
		ESPECIES.add(new Especie("BNS P/B", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE B"));
		ESPECIES.add(new Especie("BNS P/C", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE C"));
		ESPECIES.add(new Especie("BNS P/D", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE D"));
		ESPECIES.add(new Especie("BNS P/E", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE E"));
		ESPECIES.add(new Especie("BNS P/F", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE F"));
		ESPECIES.add(new Especie("BNS P/G", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE G"));
		ESPECIES.add(new Especie("BNS P/H", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE H"));
		ESPECIES.add(new Especie("BNS PRE", "BÔNUS DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS"));
		ESPECIES.add(new Especie("PCD", "POSIÇÃO CONSOLIDADA DA DIVIDA"));
		ESPECIES.add(new Especie("UP", "PRECATÓRIO"));
		ESPECIES.add(new Especie("REC", "RECIBO DE SUBSCRIÇÃO MISCELÂNEA"));
		ESPECIES.add(new Especie("ON REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES ORDINÁRIAS"));
		ESPECIES.add(new Especie("PNA REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE A"));
		ESPECIES.add(new Especie("PNB REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE B"));
		ESPECIES.add(new Especie("PNC REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE C"));
		ESPECIES.add(new Especie("PND REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE D"));
		ESPECIES.add(new Especie("PNE REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE E"));
		ESPECIES.add(new Especie("PNF REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE F"));
		ESPECIES.add(new Especie("PNG REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE G"));
		ESPECIES.add(new Especie("PNH REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS CLASSE H"));
		ESPECIES.add(new Especie("PN REC", "RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS"));
		ESPECIES.add(new Especie("PNV REC RECIBO DE SUBSCRIÇÃO EM AÇÕES PREFERENCIAIS C/ DIREITO VOTO", ""));
		ESPECIES.add(new Especie("UNT", "UNITS"));
		ESPECIES.add(new Especie("WRT", "WARRANTS DE DEBÊNTURES"));
		ESPECIES.add(new Especie("OR P", "AÇÕES ORDINÁRIAS NOMINATIVAS RESGATÁVEIS C/ DIREITOS DIF"));
		ESPECIES.add(new Especie("PRA P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE \"A\" RESG. C/ DIR.DIF"));
		ESPECIES.add(new Especie("PRB P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE \"B\" RESG. C/ DIR.DIF"));
		ESPECIES.add(new Especie("PRC P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE \"C\" RESG. C/ DIR.DIF"));
		ESPECIES.add(new Especie("PRD P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE \"D\" RESG. C/ DIR.DIF."));
		ESPECIES.add(new Especie("PRE P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE \"E\" RESG. C/ DIR.DIF"));
		ESPECIES.add(new Especie("PRF P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE \"F\" RESG. C/ DIR.DIF."));
		ESPECIES.add(new Especie("PRG P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE \"G\" RESG. C/ DIR.DIF"));
		ESPECIES.add(new Especie("PRH P", "AÇÕES PREFERENCIAIS NOMINATIVAS CLASSE \"H\" RESG. C/ DIR.DIF"));
		ESPECIES.add(new Especie("PR P", "AÇÕES PREFERENCIAIS NOMINATIVAS RESGATÁVEIS C/ DIREITOS DIF"));
		ESPECIES.add(new Especie("PRV P", "AÇÕES PREFERENCIAIS NOMINATIVAS RESG. C/ DIR.DIF. E DIR.VOTO"));

	}

	public static final List<Especie> all() {
		return ESPECIES;
	}

	public static final Especie get(String sigla) {
		for (Especie e : ESPECIES)
			if (sigla.equalsIgnoreCase(e.sigla))
				return e;
		return null;
	}

	public static final String getNome(String sigla) {
		Especie e = get(sigla);
		return e == null ? null : e.nome;
	}

}
